#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$argv = $_SERVER['argv'] ?? [];

if (($argv[1] ?? null) === 'serve' && ! in_array('--no-reload', $argv, true)) {
	$argv[] = '--no-reload';
	$_SERVER['argv'] = $argv;
	$_SERVER['argc'] = count($argv);
}

$status = $app->handleCommand(new ArgvInput);

exit($status);
